# Generated by Django 3.0.4 on 2020-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=128)),
                ('transmission', models.CharField(choices=[('MECHANIC', 'mechanic'), ('AUTO', 'auto'), ('ROBOT', 'robot')], default='MECHANIC', max_length=20)),
            ],
        ),
    ]
